pipeline:

  docker-test:
    group: build
    image: plugins/docker
    storage_driver: vfs
    repo: omelhoro1/russyll
    tags: test
    secrets: [ docker_username, docker_password ]
    dry_run: true
    dockerfile: Dockerfile.test
    when:
      branch: master

  docker:
    group: build
    image: plugins/docker
    storage_driver: vfs
    repo: omelhoro1/russyll
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  deploy:
    image: drillster/drone-rsync
    user: captain
    hosts: [ "software-unchained.com" ]
    port: 22
    target: /tmp/russyll-${DRONE_COMMIT}/
    include:
      - "docker-compose.yml"
    exclude:
      - "**.*"
    delete: false
    secrets: [ rsync_key ]
    script:
      - docker-compose -f /tmp/russyll-${DRONE_COMMIT}/docker-compose.yml pull
      - docker-compose -f /tmp/russyll-${DRONE_COMMIT}/docker-compose.yml -p russyll up -d
    when:
      branch: master
