build:
  image: clojure
  commands:
    # install node
    - apt-get install curl
    - curl --silent --location https://deb.nodesource.com/setup_7.x | bash -
    - apt-get install -y nodejs
    - npm i
    # install phantom js
    - ln -sf /drone/src/github.com/omelhoro/russyll/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /usr/local/bin
    - phantomjs -v
    # run tests
    - lein doo phantom test once

cache:
   mount:
     - node_modules
     - /root/.m2

deploy:
  rsync:
    user: $$PROD_USER
    host: $$PROD_HOST
    port: 22
    source: ./docker-compose.yml
    target: /tmp/$$COMMIT/
    delete: false
    commands:
      - docker-compose -f /tmp/$$COMMIT/docker-compose.yml pull
      - docker-compose -f /tmp/$$COMMIT/docker-compose.yml -p russyll up -d
    when:
      branch: master

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    storage_driver: vfs
    repo: omelhoro1/russyll
    when:
      branch: master
