pipeline:
  docker-test:
    group: build
    image: docker
    secrets: [docker_username, docker_password]
    commands:
      - docker build -t omelhoro1/russyll:test -f ./Dockerfile.test .
    when:
      branch: master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker:
    group: build
    image: docker
    secrets: [docker_username, docker_password]
    commands:
      - docker build -t omelhoro1/russyll:latest .
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker push omelhoro1/russyll
    when:
      branch: master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy:
    image: drillster/drone-rsync
    user: captain
    hosts: ["software-unchained.com"]
    port: 22
    target: /tmp/russyll-${DRONE_COMMIT}/
    include:
      - "docker-compose.yml"
    exclude:
      - "**.*"
    delete: false
    secrets: [rsync_key]
    script:
      - docker-compose -f /tmp/russyll-${DRONE_COMMIT}/docker-compose.yml pull
      - docker-compose -f /tmp/russyll-${DRONE_COMMIT}/docker-compose.yml -p russyll up -d
    when:
      branch: master
