FROM theasp/clojurescript-nodejs

WORKDIR /app
RUN npm i phantomjs-prebuilt
RUN ln -sf $(pwd)/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /usr/local/bin
RUN phantomjs -v
COPY ./ /app
RUN ls -na
RUN lein doo phantom test once
